---
title: "Oppgave: Filosofihistorie"
---

## Introduksjon

Dette er et arbeidskrav om "Filosofihistorie" i faget IDR4000-1 24H Kvantitativ metode og statistikk. Dette var en individuell oppgave jeg har gjort små forrandringer med og utvidet litt basert på tilbakemelding fra læreren. Vi skulle velge oss ut 2 av 3 spørsmål. Jeg valgte det første og tredje spørsmålet som handlet om Induksjon og Bayesianisme.

## Spørsmål 1: 

Ifølge Hume er det umulig å rasjonelt begrunne bruken av induksjon. Hva er argumentet for denne konklusjonen? Gi en innvending mot ett av premissene i Humes argument og prøv å svare på denne innvendingen på Humes vegne.

### Hva er induksjon, og Hume sitt argument.

Induktiv resonnering går fra det spesifikke til det generelle. En observerer mønstre eller trender i et begrenset antall tilfeller og bruker disse observasjonene til å formulere bredere generaliseringer eller teorier [@Okasha, s. 17]. Eksemplet @Okasha, bruker er: de første fem eggene i en kartong er gode. Alle eggene i kartongen har samme best-før dato stemplet på seg. Derfor er det sjette egget også god. Selv om de første fem eggene er gode, og alle eggene har samme dato stempel, er det fortsatt fult mulig at det sjette egget er råttent. Det er logisk mulig at premisset til inferensen er sant, og fortsatt at konklusjonen er falsk. Så inferensen er ikke deduktiv. Deduktiv inferens sier at hvis premisset er sant så må også konklusjonen være sann, som ved eksemplet: alle franskmenn liker rødvin, Pierre er en franskmann derfor liker Pierre rødvin [@Okasha, s. 16].

Ifølge Hume er det umulig å rasjonelt begrunne bruken av induksjon. Argumentet han bruker er at vi forutsetter eller antar «naturens uniformitet» (uniformity of nature). Vi gjør en antagelse av at eggene vi har utforsket er like som de vi ikke har utforsket [@Okasha, s. 20-21]. Hume spør hvordan vi kan bevise at en slik uniformitet er sann. Vi kan forestille oss at verden ikke er uniformell, og forandrer seg fra dag til dag. I en slik verden kan neste slurk med vann fra springen forgifte oss selv om den aldri før har gjort det. Siden vi kan forestille oss en slik verden, så kan vi ikke bevise at den uniformelle antagelsen er sann. For hvis vi kunne ville en ikke-uniformell verden være en logisk umulighet [@Okasha, s. 20].

En annen del av argumentet til Hume er at vi heller ikke kan bevise uniformitetsantagelsen induktivt. Hvis vi prøver å rettferdiggjøre induksjon ved å si at den har fungert tidligere, bruker vi nettopp den type resonnement vi forsøker å bevise. Dette skaper en sirkulær argumentasjon som ikke gir en gyldig begrunnelse for induksjon[@Okasha, s. 21-22].

### Innvending mot ett av premissene til Hume og motargument.

Hume hevder at induksjon forutsetter en tro på "naturens uniformitet", men dette premisset kan utfordres. Vi kan argumentere for at effektiv induksjon ikke nødvendigvis krever en absolutt tro på naturens uniformitet, men snarere en mer begrenset antagelse om regelmessighet innenfor spesifikke domener eller under visse forhold. For eksempel, i tilfellet med eggene, trenger vi ikke anta at hele naturen er uniform, bare at produksjons- og lagringsforholdene for eggene i én bestemt kartong sannsynligvis er konsistente. Vi trenger ikke at hele naturen skal være uniformell, men innenfor et lite begrenset område av naturen kan vi kontrollere variable nokk til at det vil være rasjonelt å forvente at det neste egget ikke vil være råttent. Denne mer begrensede antagelsen er mindre problematisk enn den universelle påstanden om naturens uniformitet som Hume kritiserer.

Jeg tror Hume svarer at selv om vi begrenser vår antagelse om uniformitet til spesifikke domener eller forhold, står vi fortsatt overfor det samme grunnleggende problemet. Hvordan kan vi rettferdiggjøre selv denne begrensede antagelsen om regelmessighet? Enhver slutning om fremtiden basert på fortiden er i seg selv en induktiv slutning, og dermed sirkulær hvis den brukes til å rettferdiggjøre induksjon [@Okasha, s. 21]. Enhver begrunnelse vi gir for å tro at produksjons- og lagringsforholdene for eggene i én kartong er konsistente, vil til syvende og sist hvile på tidligere erfaringer og observasjoner. Men å bruke disse tidligere erfaringene til å rettferdiggjøre vår tro på fremtidig regelmessighet er nettopp den typen induktiv slutning som Hume utfordrer. For hvis du hadde forsøkt å forklare induksjon til noen som ikke stoler på induksjon fra før av ville et slikt argument ikke fungere. For å argumentere at en kan stole på induksjon fordi den har fungert helt til nå er i seg selv å rasjonalisere induktivt [@Okasha, s. 21-22]. Vi har ingen garanti for at de spesifikke forholdene vi observerer i dag vil forbli konstante i fremtiden, uansett hvor begrenset domenet er.

## Spørsmål 3:

Forklar de grunnleggende ideene i Bayesianisme, samt hvordan Bayesianske sannsynligheter kan tolkes. Presenter så ett problem med Bayesianisme og evaluer hvor alvorlig problemet er.

### De grunnleggende ideene i Bayesianisme, og hvordan Bayesianske sannsynlighet kan tolkes.

Bayesianisme er en tilnærming til å forsøke å forstå bevis og bekreftelse i vitenskapen ved hjelp av matematisk sannsynlighetsteori. Den sentrale ideen er at observasjoner kan øke eller redusere sannsynligheten for en hypotese [@GodfreySmith, s. 203]. Bayesianere bruker Bayes teorem som en formel for å beregne hvordan sannsynligheten for en hypotese endres i lys av nye bevis. Formelen i sin enkleste form kan skrives som: P(h\|e) = P(e\|h)P(h) / P(e). Der h står for hypotese, e står for evidens P(h\|e) er sansynligheten for hypotesen gitt evidensen (posterior), P(e\|h) er sannsynligheten for evidensen gitt hypotesen (likelihood), P(h) er den tidligere sannsynligeheten (prior) for hypotesen og P(e) er sannsynligheten for evidensen(evidenssannsynlighet) [@GodfreySmith, s. 203-205].

De fleste forsøk på å analysere sannsynlighet har forsøkt å måle noen reelle og objektive trekk ved hendelser. Hvor sannsynlighetsverdier måler kjangsen for at noe skal skje [@GodfreySmith, s. 205]. @GodfreySmith fortsetter med å si at majoriteten av filosoferene som ønsker å bruke Bayers teorem for å forstå evidens ser på sannsynlighet som noe subjektivt. «Bayesians claim to give a theory of when a person’s total network of degrees of belief is “coherent,” or rational. They argue that a coherent set of degrees of belief has to follow the standard rules of the mathematics of probability.” [@GodfreySmith, s. 206]. Bayesianere hevder å tilby en teori som beskriver når en persons totale nettverk av tro er sammenhengende eller rasjonelle. De argumenterer for at de sammenhengende grader av tro må følge standardreglene i sannsynlighetsmatematikk. Dette innebærer at troene må være logisk konsistente og justeres i samsvar med nye bevis, slik at de danner et helhetlig system. Dette handler om den subjektive tolkningen, hvor vi rasjonaliserer våre personlige oppfatninger, og er en måte Bayesianske sannsynlighet kan tolkes [@GodfreySmith, s. 206]. Noen bayesianere ønsker å inkludere en objektiv forståelse av sannsynlighet, men dette krever mer omfattende argumenter[@GodfreySmith, s. 208]. Siden @GodfreySmith ikke utdyper dette mere forholder jeg meg til den subjektive forståelsen.

Regelen for betinget oppdatering er sentral i bayesiansk epistemologi og beskriver hvordan man bør justere sine oppfatninger når ny informasjon mottas [@Okasha, s. 32-33]. Bayes' teorem er nøkkelen til å forstå forholdet mellom sannsynligheten for en hypotese før og etter ny evidens presenteres. En rasjonell person vil, ifølge bayesianismen, oppdatere sin tro basert på denne nye informasjonen, slik at den reflekterer den oppdaterte sannsynligheten [@GodfreySmith, s. 208]. Dette betyr at dagens oppdaterte oppfatning blir grunnlaget for morgendagens vurderinger. Bayesianere hevder at denne kontinuerlige oppdateringsprosessen er essensiell for rasjonell tenkning. Det er viktig å merke seg at i den subjektive tolkningen av sannsynlighet, anses ingen oppfatning som mer korrekt enn en annen, så lenge de følger grunnleggende sannsynlighetsregler [@GodfreySmith, s. 208].

### Et problem og min evaluering av problemet med Bayesianisme.

Et problem ved Bayesiansk teori er at den ikke kan kritisere merkelig starter eller initiale sannsynlighetsfordelinger [@GodfreySmith, s. 210]. Til tross for dette hevder Bayesianere at selv om priorene kan være rare i starten, vil de "vaskes ut" av ny evidens, så lenge oppdateringen gjøres rasjonelt [@GodfreySmith, s. 210]. Startpunktet blir mindre viktig etter hvert som mer evidens tas i betraktning. Dette fenomenet kalles konvergens (convergence). Selv om to personer starter med svært ulike priorer, vil deres sannsynligheter for en hypotese bli nærmere hverandre etter hvert som de mottar samme evidens. Det kan bevises at for enhver mengde initial (utgangspunkt) uenighet er det mulig å finne nok evidens til å bringe dem nærmere hverandre. Likevel kan denne konvergensen ta lang tid, og det er ikke alltid mulig å få alle til å være enige om sannsynlighetene og disse bevisene har mange antagelser som ikke alltid stemmer i praksis[@GodfreySmith, s. 208]. Noen Bayesianere har derfor forsøkt å begrense hvordan den initiale sannsynligheter tildeles. Et problem med konvergensargumentet er at det antar at folk er enige om sannsynlighetene for evidensen gitt hypotesene (likelihoods). Men det er ikke alltid rimelig å anta at folk vil ha samme likelihoods når de er uenige om mange andre ting [@GodfreySmith, s. 208].

Selv om dette er et problem, virker det som at det er et problem som kan løses, gitt nok tid og ressurser, så lenge man følger de rasjonelle reglene og er logisk konsistente ifølge @GodfreySmith. Selv om jeg tror at i praksis vil dette være vanskelig å utføre fult ut. Et eksempel på hvordan dette problemet kan løses innenfor bayesiansk rammeverk, gitt nok tid og ressurser, er gjennom bruken av ikke-informative priorer. I tilfeller hvor vi ikke har tidligere informasjon å basere våre initiale sannsynligheter på, kan vi bruke såkalte "flate" eller "uniforme" priorer. Dette innebærer å gi alle mulige hypoteser like sannsynligheter i utgangspunktet. For eksempel, la oss si at vi introduserer en helt ny teori om universets opprinnelse. Vi har ingen tidligere data å basere våre initiale sannsynligheter på. I stedet for å la dette stoppe oss, kan vi starte med en uniform prior over alle mulige forklaringer. Etter hvert som vi samler inn data og observasjoner, vil vi oppdatere disse sannsynlighetene i henhold til Bayes' teorem. Over tid, gitt tilstrekkelig med data, vil sannsynlighetene konvergere mot de "sanne" verdiene, uavhengig av vårt initiale utgangspunkt

Hva med når teorier ikke har en prior å gå ut ifra da teorien eller hypotesen ikke tidligere har blitt tenkt på av forgjengeren? Som er tilfelle med interessante teorier vi har fått av både Copernicus, Newton og Darwin. Dette går imot regelen for betinget oppdatering da den må ha «gammel» informasjon den kan oppdatere. Den vitenskapelige sluttingen som går fra data til en helt ny teori kan ikke bli forstått med bruk av betinget oppdatering [@Okasha,s. 34]. Det virker som for meg at dette problemet kan løses ved at enhver teori eller hypotese, uansett hvor bisarr eller rar den er, er gyldig [@GodfreySmith, s. 208; @Okasha, s. 35]. Så ved tilfeller hvor en ikke har en prior å gå ut ifra kan en nesten «finne opp» (da en tro ikke er mer riktig enn en annen) en prior så lenge de rasjonelle oppdateringene følges etter det [@GodfreySmith, s. 210]. Dette viser imidlertid at Bayesian synspunkter ikke kan være den hele forklaringen på den vitenskapelige slutningen og forklarer ikke Humes problem med induksjon. Altså hvordan vi kan begrunne at fremtidige hendelser vil følge samme mønster som tidligere observerte hendelser [@Okasha, s. 35].
